# Authentication configuration

# Disable system users
!include auth-system.conf.ext

# Enable SQL users
!include auth-sql.conf.ext

# Disable plaintext authentication over non-SSL
disable_plaintext_auth = yes

# Authentication cache
auth_cache_size = 10M
auth_cache_ttl = 1 hour
auth_cache_negative_ttl = 1 hour
